dist: trusty
sudo: required
services:
- docker
before_install:
- pip install --user awscli
- npm install -g npx
- export PATH=$PATH:$HOME/.local/bin
script:
- make run
notifications:
  email:
  - dev-support@ampleforth.org
  slack: fragmentsorg:2bN0L0FCZZ0illBRyPucRZkV
